language: php

php:
  - 8.1
  - 8.2
  - 8.3

before_script:
  - composer install

script: ./vendor/bin/phpunit  --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false